version: '3'
services:
  postgres:
    image: postgres:13
    container_name: corn_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: corn_db
      TZ: America/Bogota
    ports:
      - "5432:5432"